communication:
  mode:
  - "websocket"
  - "http"
  - "mqtt"
  websocket:
    host: "0.0.0.0"
    port: 8080
    endpoint: "/ws"
    ntp_server: "0.it.pool.ntp.org"
    last_offloading_layer: 58
  http:
    host: "0.0.0.0"
    port: 8000
    endpoints:
      registration: "/api/registration" # post
      device_input: "/api/device_input" # post
      device_inference_result: "/api/device_inference_result" # post
      offloading_layer: "/api/offloading_layer" # get
    ntp_server: "0.it.pool.ntp.org"
    last_offloading_layer: 58
  mqtt:
    broker: "hostname.local"
    port: 1883

